language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

before_script:
    - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

notifications:
    flowdock: d9d29e9786ea83224219ec61abdec44f
