language: php

php:
    - 5.3
    - 5.4
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.5 WP_MULTISITE=0

before_script:
    - bundle install
    - rake setup

script: rake test

notifications:
    flowdock: d9d29e9786ea83224219ec61abdec44f
