# Create 'config.yml' to override any of these default settings.

# Database settings
db_host: 'localhost'
db_username: 'root'
db_password: 'password'
db_name_for_dev: 'smt_development'
db_name_for_test: 'smt_test'

# WordPress settings
wp_version: 'latest' # a number (4.1) or 'latest'
wp_user: 'admin'
wp_password: 'admin'
wp_email: 'you@example.com'

# Dev env settings
dev_url: 'localhost:8000'